apiVersion: apps/v1
kind: Deployment
metadata:
  name: seniors-journey-frontend
  labels:
    app.kubernetes.io/name: seniors-journey-frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: seniors-journey-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: seniors-journey-frontend
    spec:
      containers:
        - name: seniors-journey-frontend
          image: dtsrhpdevscedacr.azurecr.io/seniors-journey/seniors-journey-frontend
          ports:
            - name: http
              containerPort: 3000
          resources:
            requests:
              cpu: 250m
              memory: 2048Mi
            limits:
              cpu: 500m
              memory: 4096Mi
          livenessProbe:
            httpGet:
              path: /api/livez
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/readyz
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 5
  strategy:
    rollingUpdate:
      maxUnavailable: 0%
      maxSurge: 100%
