apiVersion: v1
kind: Service
metadata:
  name: seniors-journey-frontend
  labels:
    app.kubernetes.io/name: seniors-journey-frontend
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: seniors-journey-frontend
