apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  # commonLabels must have at least one unique label
  # per environment to ensure selectors are applied correctly
  app.kubernetes.io/environment: dev
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: seniors-journey
bases:
  - ../../applications/seniors-journey-frontend/
namePrefix: dev-
namespace: seniors-journey
resources:
  - ./ingresses.yaml
patchesStrategicMerge:
  - ./deployments.patch.yaml
  - ./services.patch.yaml
configMapGenerator:
  - name: seniors-journey-frontend
    options:
      labels:
        app.kubernetes.io/name: seniors-journey-frontend
    literals: [] # placeholder for future config; see: https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/configmapgenerator/
  - name: seniors-journey-frontend-auth
    options:
      labels:
        app.kubernetes.io/name: seniors-journey-frontend-auth
    files:
      - oauth-proxy.cfg
secretGenerator:
  - name: seniors-journey-frontend
    options:
      labels:
        app.kubernetes.io/name: seniors-journey-frontend
    envs:
      - .env.seniors-journey-frontend
  - name: seniors-journey-frontend-auth
    options:
      labels:
        app.kubernetes.io/name: seniors-journey-frontend-auth
    envs:
      - .env.seniors-journey-frontend-auth
