apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  # commonLabels must have at least one unique label
  # per environment to ensure selectors are applied correctly
  app.kubernetes.io/environment: production
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: seniors-journey
bases:
  - ../../applications/seniors-journey-frontend/
namespace: seniors-journey
resources:
  - ./ingresses.yaml
patchesStrategicMerge:
  - ./deployments.patch.yaml
  - ./services.patch.yaml
configMapGenerator:
  - name: seniors-journey-frontend
    options:
      labels:
        app.kubernetes.io/name: seniors-journey-frontend
    literals:
      - NEXT_PUBLIC_ADOBE_ANALYTICS_SCRIPT_SRC=https://assets.adobedtm.com/be5dfd287373/9b9cb7867b5b/launch-59d77766b86a.min.js
      - NEXT_PUBLIC_ANALYTICS_BEACON_DELAY=500
      - NEXT_PUBLIC_APP_BASE_URI=https://retraite-retirement.service.canada.ca/
      - NEXT_PUBLIC_ENVIRONMENT=prod
      - OTEL_ENVIRONMENT=production
      - OTEL_METRICS_ENDPOINT=https://dynatrace.prod-dp.admin.dts-stn.com/e/676a0299-9802-4933-99d4-481318a557db/api/v2/otlp/v1/metrics
      - OTEL_TRACES_ENDPOINT=https://dynatrace.prod-dp.admin.dts-stn.com/e/676a0299-9802-4933-99d4-481318a557db/api/v2/otlp/v1/traces
  - name: seniors-journey-frontend-auth
    options:
      labels:
        app.kubernetes.io/name: seniors-journey-frontend-auth
    files:
      - oauth-proxy.cfg
secretGenerator:
  - name: seniors-journey-frontend
    options:
      labels:
        app.kubernetes.io/name: seniors-journey-frontend
    envs:
      - .env.seniors-journey-frontend
  - name: seniors-journey-frontend-auth
    options:
      labels:
        app.kubernetes.io/name: seniors-journey-frontend-auth
    envs:
      - .env.seniors-journey-frontend-auth
