name: End-to-end tests
on:
  pull_request:
    branches: [main]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        env:
          OAUTH_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
          OAUTH_CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}
          OAUTH_ENABLED: ${{ secrets.OAUTH_ENABLED }}
          OAUTH_SCOPE: ${{ secrets.OAUTH_SCOPE }}
          OAUTH_TOKEN_URL: ${{ secrets.OAUTH_TOKEN_URL }}
